(async()=>{
const store=document.querySelector('[data-itm-store]');
if(!store)return;
const project=store.dataset.projectId||"281a419a-ce5a-4402-bc18-6fa46e6c212f";
const list=store.querySelector('[data-itm-product-list]');
const cardTemplate=store.querySelector('template[data-itm-product-card]');
const detail=store.querySelector('[data-itm-product-detail]');
const cartBox=store.querySelector('[data-itm-cart]');
const cartTemplate=cartBox?.querySelector('template[data-itm-cart-item]');
const checkout=store.querySelector('[data-itm-checkout]');
const statusNode=store.querySelector('[data-itm-store-status]');
if(!list||!cardTemplate||!detail||!cartBox||!cartTemplate||!checkout){if(statusNode)statusNode.textContent='La tienda no tiene todos sus componentes configurados.';return;}
store.dataset.itmStoreLive='true';
const products=[];const cart=new Map();
const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const imageOf=product=>product.media?.[0]?.source_url||product.image_url||'';
const setText=(scope,selector,value)=>{const node=scope.querySelector(selector);if(!node)return;if(node.matches('input,textarea,select'))node.value=value??'';else node.textContent=value??'';};
const setImage=(scope,selector,url,alt)=>{const node=scope.querySelector(selector);if(!node)return;node.src=url||'';node.alt=alt||'';node.hidden=!url;};
const productCard=(product)=>{const fragment=cardTemplate.content.cloneNode(true);const card=fragment.firstElementChild||fragment.querySelector('*');if(!card)return fragment;card.dataset.itmProductCardInstance='true';card.dataset.itmProductId=product.id;card.dataset.searchText=[product.name,product.description,product.category].join(' ').toLowerCase();setImage(card,'[data-itm-product-image]',imageOf(product),product.name);setText(card,'[data-itm-product-name]',product.name);setText(card,'[data-itm-product-description]',product.description||'');setText(card,'[data-itm-product-category]',product.category||'');setText(card,'[data-itm-product-price]',product.price==null?'Consultar':(product.currency||'MXN')+' '+product.price);card.querySelectorAll('[data-itm-product-open],[data-itm-cart-add]').forEach(button=>{button.dataset.productId=product.id;});return fragment;};
const renderProducts=()=>{list.querySelectorAll('[data-itm-product-card-instance]').forEach(node=>node.remove());const fragment=document.createDocumentFragment();products.forEach(product=>fragment.appendChild(productCard(product)));list.appendChild(fragment);if(statusNode)statusNode.textContent=products.length?'':'No hay productos publicados.';};
const searchInput=store.querySelector('[data-itm-product-search]');const categoryFilter=store.querySelector('[data-itm-product-category-filter]');const filterProducts=()=>{const query=(searchInput?.value||'').trim().toLowerCase();const category=categoryFilter?.value||'';list.querySelectorAll('[data-itm-product-card-instance]').forEach(card=>{const product=products.find(item=>item.id===card.dataset.itmProductId);const matchesQuery=!query||card.dataset.searchText.includes(query);const matchesCategory=!category||product?.category===category;card.hidden=!(matchesQuery&&matchesCategory);});};
const showDetail=product=>{detail.dataset.productId=product.id;setImage(detail,'[data-itm-detail-image]',imageOf(product),product.name);setText(detail,'[data-itm-detail-name]',product.name);setText(detail,'[data-itm-detail-description]',product.description||'');setText(detail,'[data-itm-detail-category]',product.category||'');setText(detail,'[data-itm-detail-price]',product.price==null?'Consultar':(product.currency||'MXN')+' '+product.price);const quantity=detail.querySelector('[data-itm-detail-quantity]');if(quantity)quantity.value='1';detail.hidden=false;if(typeof detail.showModal==='function'&&detail.tagName==='DIALOG'&&!detail.open)detail.showModal();};
const hideDetail=()=>{if(typeof detail.close==='function'&&detail.tagName==='DIALOG'&&detail.open)detail.close();detail.hidden=true;};
const addToCart=(product,quantity=1)=>{const current=cart.get(product.id);cart.set(product.id,{product,quantity:(current?.quantity||0)+Math.max(1,Number(quantity)||1)});renderCart();};
const renderCart=()=>{const items=cartBox.querySelector('[data-itm-cart-items]');if(!items)return;items.querySelectorAll('[data-itm-cart-item-instance]').forEach(node=>node.remove());const fragment=document.createDocumentFragment();let total=0;for(const line of cart.values()){const row=cartTemplate.content.cloneNode(true);const node=row.firstElementChild||row.querySelector('*');if(!node)continue;node.dataset.itmCartItemInstance='true';node.dataset.productId=line.product.id;setText(node,'[data-itm-cart-name]',line.product.name);setText(node,'[data-itm-cart-price]',line.product.price==null?'Consultar':(line.product.currency||'MXN')+' '+line.product.price);const quantity=node.querySelector('[data-itm-cart-quantity]');if(quantity)quantity.value=String(line.quantity);const lineTotal=Number(line.product.price||0)*line.quantity;total+=lineTotal;setText(node,'[data-itm-cart-line-total]',(line.product.currency||'MXN')+' '+lineTotal.toFixed(2));fragment.appendChild(row);}items.appendChild(fragment);setText(cartBox,'[data-itm-cart-total]',(products[0]?.currency||'MXN')+' '+total.toFixed(2));const empty=cartBox.querySelector('[data-itm-cart-empty]');if(empty)empty.hidden=cart.size>0;};
const apiError=async response=>{const value=await response.json().catch(()=>({}));if(!response.ok||value.ok===false)throw new Error(value.code||value.message||'No se pudo completar la operación.');return value;};
try{const response=await fetch("https://itm-void-excepcional.pages.dev/api/store-products?public=1&project_id="+encodeURIComponent(project),{cache:'no-store'});const data=await apiError(response);products.push(...(Array.isArray(data.products)?data.products:[]));renderProducts();renderCart();filterProducts();if(searchInput)searchInput.addEventListener('input',filterProducts);if(categoryFilter)categoryFilter.addEventListener('change',filterProducts);
list.addEventListener('click',event=>{const open=event.target.closest('[data-itm-product-open]');const add=event.target.closest('[data-itm-cart-add]');const productId=open?.dataset.productId||add?.dataset.productId;if(!productId)return;const product=products.find(item=>item.id===productId);if(!product)return;if(open)showDetail(product);else addToCart(product,1);});
detail.addEventListener('click',event=>{if(event.target.closest('[data-itm-detail-close]'))return hideDetail();if(!event.target.closest('[data-itm-detail-add]'))return;const product=products.find(item=>item.id===detail.dataset.productId);if(product)addToCart(product,detail.querySelector('[data-itm-detail-quantity]')?.value||1);hideDetail();});
cartBox.addEventListener('click',event=>{const remove=event.target.closest('[data-itm-cart-remove]');if(remove){cart.delete(remove.dataset.productId);renderCart();}});cartBox.addEventListener('change',event=>{const quantity=event.target.closest('[data-itm-cart-quantity]');if(!quantity)return;const line=cart.get(quantity.closest('[data-itm-cart-item-instance]')?.dataset.productId);if(line){line.quantity=Math.max(1,Number(quantity.value)||1);renderCart();}});
checkout.addEventListener('submit',async event=>{event.preventDefault();try{if(!cart.size)throw new Error('Agrega al menos un producto.');const name=checkout.querySelector('[data-itm-customer-name]')?.value.trim();const code=checkout.querySelector('[data-itm-payment-code]')?.value.trim();const status=checkout.querySelector('[data-itm-checkout-status]');if(!name)throw new Error('Escribe tu nombre.');if(!code)throw new Error('Escribe el código de pago.');if(status)status.textContent='Creando pedido...';const orderResponse=await fetch("https://itm-void-excepcional.pages.dev/api/store-orders?public=1&project_id="+encodeURIComponent(project),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_name:name,items:[...cart.values()].map(line=>({product_id:line.product.id,quantity:line.quantity}))})});const order=await apiError(orderResponse);if(status)status.textContent='Validando pago...';const paymentResponse=await fetch("https://itm-void-excepcional.pages.dev/api/store-orders?public=1&pay=1&project_id="+encodeURIComponent(project),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order_id:order.order.id,code})});const payment=await apiError(paymentResponse);if(status)status.textContent='Compra confirmada. Pedido '+payment.order.id.slice(0,8);cart.clear();renderCart();}catch(error){const status=checkout.querySelector('[data-itm-checkout-status]');if(status)status.textContent=error.message||'No se pudo completar la compra.';}});
checkout.querySelectorAll('[data-itm-pay]').forEach(button=>{if(button.type!=='submit')button.addEventListener('click',()=>checkout.requestSubmit());});
}catch(error){if(statusNode)statusNode.textContent=error.message||'No se pudo cargar la tienda.';}
})();